### ISSUE TITLE
Error on backup

### ISSUE THREAD

**Issue by peptoniet** [waja/docker-calcardbackup#17]
On versions later than 2.1.1-3 running the backup job gives me this error in the log:

ERROR: can't read '/opt/calcardbackup/calcardbackup'. Check given path!

Running the backup command on the docker image console gives me the same error.

Version 2.1.1-3 works correctly.
3.0.0-1 fails.

**Comment by waja** [comment]
> On versions later than 2.1.1-3 running the backup job gives me this error in the log:
> 
> ERROR: can't read '/opt/calcardbackup/calcardbackup'. Check given path!
> 
> Running the backup command on the docker image console gives me the same error.

when running `/opt/calcardbackup/calcardbackup` inside of the container:

```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+  Tue Jul  6 19:17:39 CEST 2021 --> START calcardbackup ver. 3.0.0 (01.07.2021), AGPL-3.0
+  Checking dependencies and preparing...
-- calcardbackup: ERROR --
-- ERROR: can't read '/opt/calcardbackup/calcardbackup.conf'. Check given path!
-- I need to be able to read the full path!
-- calcardbackup: Exiting.

-- calcardbackup: ERROR --
-- Error in command: "config_file="$(get_absolute_path_ng "${config_file}")""
-- calcardbackup: Exiting.
```

When running `/opt/calcardbackup/calcardbackup /nextcloud/ --output /backup/ -i` which is the [default](https://github.com/waja/docker-calcardbackup/blob/development/run.sh#L2):

```
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+  Tue Jul  6 19:24:59 CEST 2021 --> START calcardbackup ver. 3.0.0 (01.07.2021), AGPL-3.0
+  Checking dependencies and preparing...
+  no usersfile given:
+     - will fetch all available items from database
+     - will not backup shared items additionally
[...]
```

So I can't reproduce the reported issue.

**Comment by peptoniet** [comment]
Hello,
Thank you for checking.
I tried the same exact command and I get this error:

```
bash-5.1# /opt/calcardbackup/calcardbackup /nextcloud --output /backup/ -i
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+  Tue Jul  6 22:31:02 CEST 2021 --> START calcardbackup ver. 3.0.0 (01.07.2021), AGPL-3.0
-- calcardbackup: ERROR --
-- ERROR: can't read '/opt/calcardbackup/calcardbackup'. Check given path!
-- I need to be able to read the full path!
-- calcardbackup: Exiting.

-- calcardbackup: ERROR --
-- Error in command: "script_dir="$(get_absolute_path_ng "${BASH_SOURCE[0]}")""
-- calcardbackup: Exiting.
```

The relevant part of the docker-compose.yaml is:

```
  nextcloud-nc-backup:
    image: waja/calcardbackup
    links:
      - db:nextcloud-db
      - nextcloud:nextcloud
    environment:
      - CRON_TIME=0 14,20 * * *
      - CALCARD_OPTS=-i -x -r 10 -d -%Y-%m-%d-%H-%M
      - NC_DIR=/nextcloud
      - NC_HOST=nextcloud
      - NC_PORT=80
      - DB_HOST=db
    depends_on:
      - db
      - nextcloud
    restart: unless-stopped
    volumes:
      - /data/OwnCloudData/calcardbackup:/backup
      - ./nextcloud/config:/nextcloud/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      static-network:
        ipv4_address: 172.91.91.95
```
